[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
lazorkit = "33tS3mSoyvdmKWxb6bgSL657AqH4Wxsu9R6GnvjtZdEd"
transfer_limit = "EXYavpYDn6twyPvsGtvuJkEaGeqbN5TLCnC3Fp3evv85"
default_rule = "scdFpnHi1Hu1BbKPwEdhRcdWwu5DohSWxCAg3UeDNKZ"

[programs.localnet]
lazorkit = "33tS3mSoyvdmKWxb6bgSL657AqH4Wxsu9R6GnvjtZdEd"
transfer_limit = "EXYavpYDn6twyPvsGtvuJkEaGeqbN5TLCnC3Fp3evv85"
default_rule = "scdFpnHi1Hu1BbKPwEdhRcdWwu5DohSWxCAg3UeDNKZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"
