export enum ErrorCode {
  // Connection errors
  CONNECTION_FAILED = 'CONNECTION_FAILED',
  NOT_CONNECTED = 'NOT_CONNECTED',
  ALREADY_CONNECTED = 'ALREADY_CONNECTED',
  
  // Authentication errors  
  INVALID_SIGNATURE = 'INVALID_SIGNATURE',
  AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
  USER_CANCELLED = 'USER_CANCELLED',
  
  // Transaction errors
  SIGN_FAILED = 'SIGN_FAILED',
  TRANSACTION_FAILED = 'TRANSACTION_FAILED',
  INVALID_TRANSACTION = 'INVALID_TRANSACTION',
  
  // Dialog errors
  DIALOG_ERROR = 'DIALOG_ERROR',
  POPUP_BLOCKED = 'POPUP_BLOCKED',
  
  // Bridge errors
  BRIDGE_ERROR = 'BRIDGE_ERROR',
  TIMEOUT = 'TIMEOUT',
  CLOSED = 'CLOSED',
  
  // General errors
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  INVALID_CONFIG = 'INVALID_CONFIG',
  NETWORK_ERROR = 'NETWORK_ERROR'
}